[db]
major_version = 15

[functions.discord-interactions]
entrypoint = "./edge-functions/discord-interactions/index.ts"
verify_jwt = false

[functions.discord-campaign-bot]
entrypoint = "./edge-functions/discord-campaign-bot/index.ts"

[functions.users-images-cleanup-drafts]
entrypoint = "./edge-functions/users-images-cleanup-drafts/index.ts"
