/**
 * EquipmentGrantOption - a single option in an equipment grants configuration
 */
export interface EquipmentGrantOption {
  equipment_id: string;
  additional_cost: number;
  equipment_name?: string; // Enriched by RPC
}

/**
 * EquipmentGrants - configuration for equipment that grants other equipment
 * - fixed: Automatically grants all options, no user choice
 * - single_select: User must choose exactly one option
 * - multiple_select: User can choose up to max_selections options
 */
export interface EquipmentGrants {
  selection_type: "fixed" | "single_select" | "multiple_select";
  max_selections?: number;
  options: EquipmentGrantOption[];
}

/**
 * WeaponProfile - canonical type for weapon profiles
 * Fields are flexible (number | string | null) because:
 * - Database can return either format
 * - Effect modifiers can produce strings like "6+" for ammo
 */
export interface WeaponProfile {
  id: string;
  profile_name: string;
  range_short?: number | string | null;
  range_long?: number | string | null;
  acc_short?: number | string | null;
  acc_long?: number | string | null;
  strength?: number | string | null;
  ap?: number | string | null;
  damage?: number | string | null;
  ammo?: number | string | null;
  traits?: string | null;
  weapon_group_id?: string | null;
  is_master_crafted?: boolean;
  sort_order?: number | null;
}

/**
 * WeaponProfileInput - type for creating/editing weapon profiles in forms
 * All fields are strings for form input, no id field (generated by DB)
 */
export interface WeaponProfileInput {
  profile_name: string;
  range_short: string;
  range_long: string;
  acc_short: string;
  acc_long: string;
  strength: string;
  ap: string;
  damage: string;
  ammo: string;
  traits: string;
  weapon_group_id?: string | null;
  sort_order: number;
}

/**
 * Weapon - simplified weapon type used in fighter cards and roster views
 */
export interface Weapon {
  fighter_weapon_id: string;
  weapon_id: string;
  weapon_name: string;
  weapon_profiles: WeaponProfile[];
  effect_names?: string[]; // Names of effects that target this weapon
}

export interface Equipment {
  fighter_equipment_id: string;
  fighter_weapon_id?: string;
  equipment_id: string;
  equipment_name: string;
  equipment_type: 'weapon' | 'wargear' | 'vehicle_upgrade';
  cost: number;
  base_cost?: number;
  discounted_cost?: number;
  adjusted_cost?: number;
  availability?: string | null;
  equipment_category?: string;
  created_at?: string;
  weapon_profiles?: WeaponProfile[] | null;
  base_weapon_profiles?: WeaponProfile[] | null; // Original profiles before effects applied (for optimistic updates)
  core_equipment?: boolean;
  vehicle_upgrade_slot?: string;
  target_equipment_id?: string | null; // For equipment-to-equipment upgrades
  effect_names?: string[]; // Names of effects that target this equipment
  granted_by_equipment_id?: string | null; // ID of parent equipment that granted this item
  grants_equipment?: EquipmentGrants | null;

  master_crafted?: boolean;
  is_master_crafted?: boolean;
  is_custom?: boolean;
  is_editable?: boolean;
  loadout_ids?: string[]; // Which loadout IDs this equipment belongs to
  fighter_type_equipment?: boolean;
  equipment_tradingpost?: boolean;
  trading_post_names?: string[];
  from_fighters_list?: boolean;
}

/**
 * FighterLoadout - represents a fighter's equipment loadout
 */
export interface FighterLoadout {
  id: string;
  fighter_id: string;
  loadout_name: string;
  equipment_ids: string[];  // fighter_equipment_ids in this loadout
}

/**
 * CustomEquipment - user-created custom equipment
 */
export interface CustomEquipment {
  id: string;
  user_id: string;
  equipment_name: string;
  availability: string;
  cost: number;
  faction?: string;
  variant?: string;
  equipment_category?: string;
  equipment_category_id?: string;
  equipment_type?: string;
  created_at: string;
  updated_at?: string;
}

/**
 * CustomWeaponProfileData - type for creating/editing custom weapon profiles
 * Similar to WeaponProfileInput but with optional fields for custom profiles
 */
export interface CustomWeaponProfileData {
  profile_name?: string;
  range_short: string;
  range_long: string;
  acc_short: string;
  acc_long: string;
  strength: string;
  ap: string;
  damage: string;
  ammo: string;
  traits?: string;
  sort_order?: number;
}
