export const equipmentCategoryRank: { [key: string]: number } = {
  ammunition: 0,
  'special ammunition': 1,
  //
  'basic weapons': 10,
  pistols: 11,
  'special weapons': 12,
  'heavy weapons': 13,
  'power pack weapons': 14,
  'close combat weapons': 15,
  grenades: 16,
  'booby traps': 17,
  //
  armour: 30,
  'field armour': 31,
  bionics: 32,
  'archaeo-cyberteknika': 33,
  'gang equipment': 34,
  'spyrer equipment': 35,
  'personal equipment': 36,
  mounts: 37,
  chems: 38,
  'chem alchemy': 39,
  'weapon accessories': 40,
  'status items: exotic beasts': 41,
  'status items: extravagant goods': 42,
  'status items: servo skulls': 43,
  //
  vehicles: 50,
  'cargo loads': 51,
  'vehicle upgrades': 52,
  'vehicle wargear': 53,
  //
  'special terrain': 60,
};
