export const skillSetRank: { [key: string]: number } = {
  "agility": 1,
  "brawn": 2,
  "combat": 3,
  "cunning": 4,
  "driving": 5,
  "ferocity": 6,
  "leadership": 7,
  "savant": 8,
  "shooting": 9,
  //
  "bravado": 10,
  "finesse": 11,
  "muscle": 12,
  "obfuscation": 13,
  "palanite drill": 14,
  "piety": 15,
  "savagery": 16,
  "tech": 17,
  "wastelands": 18,
  "wisdom of the ancients": 19,
  //
  "wyrd powers (core rulebook)": 20,
  "wyrd powers: biomancy": 21,
  "wyrd powers: chronomancy": 22,
  "wyrd powers: divination": 23,
  "wyrd powers: pyromancy": 24,
  "wyrd powers: technomancy": 25,
  "wyrd powers: telepathy": 26,
  "wyrd powers: telekinesis": 27,
  //
  "chaos cult wyrd powers": 28,
  "genestealer cult wyrd powers": 29,
  "ogryn wyrd powers": 30,
  //
  "psychoteric whispers: madness": 31,
  "psychoteric whispers: darkness": 32,
  "psychoteric whispers: delusion": 33,
  //
  "legendary names: impressive leadership": 34,
  "legendary names: improbable beatdowns": 35,
  "legendary names: incredible drives": 36,
  "legendary names: unbelievable escapes": 37,
};
